package app.web;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class CommentDao {

    public void init() throws SQLException {
        String sql =
                "create table if not exists comments(" +
                "id bigint generated by default as identity primary key," +
                "author varchar(64) not null," +
                "text varchar(1000) not null," +
                "created_at timestamp not null default current_timestamp" +
                ")";

        try (var connection = Db.get();
             var statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    public long add(String author, String text) throws SQLException {
        String sql =
                "insert into comments(author, text) values (?, ?)";

        try (var connection = Db.get();
             var statement = connection.prepareStatement(
                     sql,
                     java.sql.Statement.RETURN_GENERATED_KEYS)) {

            statement.setString(1, author);
            statement.setString(2, text);
            statement.executeUpdate();

            try (var keys = statement.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getLong(1);
                }
            }
        }

        throw new SQLException("Could not obtain generated comment id");
    }

    public List<Map<String, Object>> list() throws SQLException {
        String sql =
                "select id, author, text, created_at " +
                "from comments order by id desc";

        try (var connection = Db.get();
             var statement = connection.prepareStatement(sql);
             var resultSet = statement.executeQuery()) {

            var result = new ArrayList<Map<String, Object>>();

            while (resultSet.next()) {
                result.add(Map.of(
                        "id", resultSet.getLong("id"),
                        "author", resultSet.getString("author"),
                        "text", resultSet.getString("text"),
                        "createdAt", resultSet.getTimestamp("created_at")
                                .toInstant()
                                .toString()
                ));
            }

            return result;
        }
    }
}
